// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function LoadCommandsDataString() {
  return window['go']['main']['App']['LoadCommandsDataString']();
}
